security:
  oauth2:
    client:
      client-id: 233668646673605
      token-name: oauth_token
      authentication-scheme: query
      client-authentication-scheme: form
      access-token-uri: https://graph.facebook.com/oauth/access_token
      user-authorization-uri: https://www.facebook.com/dialog/oauth
    resource:
      user-info-uri: https://graph.facebook.com/me
      client-id: 233668646673605
      client-secret: 33b17e044ee6a4fa383f46ec6e28ea1d
      token-type: code

multipart:
    maxFileSize: 5MB
    maxRequestSize: 5MB

# spring already does JSR-303 bean validation. no need for hibernate validation
spring.jpa.properties.javax.persistence.validation.mode: none

server.compression.enabled: true
server.compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

spring.resources.cache-period: 3600


spring:
    datasource.platform: h2


logging:
    level:
        root: INFO
        org.springframework.security: DEBUG
    path: logs



